services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: heatbeat-control-backend
    environment:
      - DATABASE_URL=sqlite:///./heatbeat.db
      - JWT_SECRET=dev_secret_change_me
    volumes:
      - backend_data:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: heatbeat-control-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_data:
