version: "3.9"
services:
  api:
    build: ./backend
    container_name: heatbeat_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./heatbeat.db   # Na start SQLite (prosto). Zmienisz na Postgres później.
      - JWT_SECRET=super_tajne_haslo_zmien_mnie
      - TZ=Europe/Warsaw
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    container_name: heatbeat_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
